spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/tourofheroes
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
management:
  endpoints:
    web:
      exposure:
        include: "*"